version: "3"

services:
    backend:
        image: strapi/strapi
        container_name: backend_strapi
        restart: unless-stopped
        env_file: .env
        environment:
            DATABASE_CLIENT: ${DATABASE_CLIENT}
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_HOST: ${DATABASE_HOST}
            DATABASE_PORT: ${DATABASE_PORT}
            DATABASE_USERNAME: ${DATABASE_USERNAME}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
        volumes:
            - ./app:/srv/app
        ports:
            - "1337:1337"
        networks:
            - strapi-app-network

    mongodb:
        image: mongo
        container_name: mongo_strapi
        restart: unless-stopped
        env_file: .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        volumes:
            - strapidata:/data/db
        ports:
            - "27017:27017"
        networks:
            - strapi-app-network

networks:
    strapi-app-network:
        driver: bridge

volumes:
    strapidata:
